server:
  port: 8888
  #context-path: /nut
spring:
  http:
    encoding:
      charset: UTF-8
      force: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/project?useUnicode=true&characterEncoding=UTF-8&autoReconnectForPools=true&serverTimezone=Hongkong
    username: root
    password: 123456
    name: druid
    druid:
      initialSize: 2
      minIdle: 2
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 3600000
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: true
      testOnReturn: false
    redis:
      host: 192.168.75.132
      port: 6379
      #swagger
swagger:
  basePackage: com.nut.web
  title: 坚果宝宝
  description: 我爱java，学习使我快乐
  version: V1.0
#mybatis 配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml




